services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.cloudrun
    container_name: ddp_api_cloudrun_local
    ports:
      - "8085:8080"
    env_file:
      - .env
    environment:
      APP_URL: http://localhost:8085
      LOG_CHANNEL: stderr

      # DB harus pakai network docker: host=db port=3306
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ddp_api
      DB_USERNAME: ddp_user
      DB_PASSWORD: ddp_pass
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: ddp_api_cloudrun_db
    environment:
      MYSQL_DATABASE: ddp_api
      MYSQL_USER: ddp_user
      MYSQL_PASSWORD: ddp_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3308:3306"   # ini hanya untuk akses dari Windows (opsional)
    volumes:
      - dbdata_cloudrun:/var/lib/mysql

volumes:
  dbdata_cloudrun:

